defaults:
    - hydra/job_logging: colorlog
    - hydra/hydra_logging: colorlog
hydra:
    run:
        # constant if you want to resume the training
        dir: ./outputs/exp1 #./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
training:
    resume: true
    # reproduce
    random_seed: 123
    num_gpus_per_node: 1
    # Mixed Precision
    fp16: true
    fp16_opt_level: "O1" # O0 to disable fp16
    # Optimization
    learning_rate: 1e-3
    gradient_accumulation_steps: 1
    max_gradient_norm: 1.0 # disabled when negative. used for clip_grad_norm
    optimizer: "AdamW"
    scheduler: "WarmupLinear" # WarmupConstant, WarmupLinear, WarmupCosine, WarmupCosineWithHardRestarts
    weight_decay: 0.01
    warmup_steps: 100 # disabled when negative 
    batch_size: 64
    total_num_epochs: 3
    total_num_update_steps: 10 # disabled when total_num_epochs > 0
saving:
    # when saving.steps_interval and saving.seconds_interval
    # are both negative, save the models for every epoch
    steps_interval: -1
    seconds_interval: 2 # disabled when steps_interval > 1
    # checkpointer
    num_checkpoints_to_keep: 2
    keep_checkpoint_every_num_seconds: 3600
    resume_mode: true
logging:
    color: true
    level: "INFO"
    steps_interval: -1 # disabled when negative
    seconds_interval: 2 # disabled when `log_steps_interval` is set