name: torchfly
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pytorch
  - torchvision
#  - cudatoolkit=10.1
  - pip:
    - absl-py==0.9.0
    - ray
    - regex
    - transformers==2.5.1
    - hydra-core
    - hydra-colorlog
    - colorlog
    - tensorboard
    - tqdm
    - gdown
    - scikit-learn
    - overrides
    - pyarrow